version: '3'

services:
  nginx:
    build: ./etc/dev/nginx
    volumes:
    - ./etc/dev/logs/:/var/log/nginx:cached
    - ./etc/dev/ssl:/etc/ssl
    - ./etc/dev/nginx/default-symfony.template.conf:/etc/nginx/conf.d/default.template
    - ./etc/dev/nginx/default-symfony.conf:/etc/nginx/conf.d/default.conf
    - ./etc/dev/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
    - ./etc/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
    - .:/var/www/html
    ports:
    - "${NGINX_HOST_PORT}:80"
    - "${NGINX_HOST_SSH_PORT}:443"
    env_file:
    - ./.env
    environment:
    - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
    - php
    - mysql

  php:
    build: ./etc/dev/php
    restart: always
    env_file:
    - ./.env
    ports:
    - "${PHP_HOST_PORT}:9000"
    volumes:
    - ./etc/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./etc/dev/php/symfony.pool.conf:/etc/php7/php-fpm.d/symfony.pool.conf
    - .:/var/www/html
    extra_hosts:
    - .host:${HOST_IP}
    depends_on:
    - mysql

  mysql:
    image: mysql
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --default-authentication-plugin=mysql_native_password
    ports:
    - "${MYSQL_HOST_PORT}:3306"
    env_file:
    - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    volumes:
    - "./data/db/mysql:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_PORT=3306
    ports:
    - "${PMA_HOST_PORT}:80"
    restart: always
    depends_on:
    - mysql